name: polymerjs
version: 0.0.1
author: Kasper Peulen
description: polymer.js 1.0 wrapper
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  web_components: any
dev_dependencies:
  test: any
  grinder: any
transformers:
- web_components:
    entry_points:
      - test/custom_element/index_test.html
      - web/index.html
- test/pub_serve:
    $include:
      - test/custom_element/**.dart
      - test/**.dart